### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by davids1030** [CheeseDanish1/Rosetta-Stone-Hack#1]
Hi I dont know how to exactly use this, pls can you share a video? I can pay you Paypal if it works, thank you in advance. dmsoportes@gmail.com

**Comment by davids1030** [comment]
Or at least tell me how to put the corrects tokens, where do i get from? I think I am failing in that.

**Comment by CheeseDanish1** [comment]
I can't send a video as I no longer have access to my Rosetta stone account.

Open the network tab (control+shift+i then network) and refresh the page on the main dashboard. Look for a request titled graphql. In the request header options you should find an authentication token and a session token. Then in a different request, the user id will be in the url after /users. There isn't a specific one so just find a random one.

If you can't get this to work, there is a slower method which I do have a video for. Basically you send the network requests one by one instead of all at once like the code does. I'll include a video of that. In fact, all this code does is get a list of all the lessons and then send the request shown in the video one by one.

If you can't get the primary technique to work and still want to then just respond and I'll email you about a discord call or something else. Good Luck!

https://github.com/CheeseDanish1/Rosetta-Stone-Hack/assets/65871181/3ec8781b-11d5-46b0-8906-e76b4b10c636

**Comment by tmfawop** [comment]
I may need more of an explanation, im not showing the same sources in my network tab. please help.

owensjarrard@gmail.com

**Comment by Nervatrons** [comment]
> I may need more of an explanation, im not showing the same sources in my network tab. please help.
> 
> [owensjarrard@gmail.com](mailto:owensjarrard@gmail.com)

Hi man, please use Firefox and you will see exactly what he is doing.

**Comment by Nervatrons** [comment]
Thank you very much

**Comment by Cubinster** [comment]
Even if it says 100 complete when i go back in everything is not done

**Comment by Cubinster** [comment]
can someone email me or set up a discord call cause idk how this works my discord is     scumli
